---
- hosts: rabbit
  vars:
    password: zoblesmouches42
  tasks:
  - name: delete 127.0.1.1 line in /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.1\.1.+'
      state: absent
  - name: delete ipv6 lines in /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: 'ip6'
      state: absent
  - name: add hosts in /etc/hosts
    lineinfile:
      dest: /etc/hosts
      line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
      state: present
      regexp: '.*{{ hostvars[item].inventory_hostname }}$'
    with_items: "{{ groups.all }}"

  - name: install rabbitmq-server
    apt: name=rabbitmq-server state=latest
  - name: restrict rabbitmq address
    lineinfile: path=/etc/rabbitmq/rabbitmq-env.conf insertafter="#NODE_IP_ADDRESS=127.0.0.1" regexp="^NODE_IP_ADDRESS=" line="NODE_IP_ADDRESS={{hostvars[inventory_hostname]['ansible_ens5']['ipv4']['address']}}"
  - name: check openstack user
    shell: rabbitmqctl list_users | grep -q openstack
    register: user
    ignore_errors: True
  - name: create rabbitmq openstack user
    command: rabbitmqctl add_user openstack {{ password }}
    when: user|failed
  - name: configure rights
    command: rabbitmqctl set_permissions openstack ".*" ".*" ".*"
    when: user|failed
